# Generated by Django 6.0.2 on 2026-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
