# Generated by Django 6.0.2 on 2026-02-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_evento_quantidade_pessoas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='quantidade_pessoas',
            new_name='quantidade_participantes',
        ),
    ]
